/* generated by quant/export.py - per-model engine configuration */
#ifndef RF_CFG_H
#define RF_CFG_H
#define RF_K_MAX 8
#define RF_DIM 128
#define RF_DEPTH 8
#define RF_HEADS 4
#define RF_TOKENS 64
#define RF_ZCH 8
#define RF_ZHW 16
#define RF_PATCH 2
#define RF_PD 32
#define RF_COND 5
#define RF_IMG_CH 3
#define RF_IMG_HW 128
#define RF_MAX_DEC 16
#define RF_DEC_NZ_MAX 1024
#define RF_DEC_W_MAX 128
#define RF_DEC_O_MAX 64
#define RF_HIRES 0
#define RF_HIRES_CMID 0
#define RF_OUT_HW 128
#endif
